name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-17"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
DATABASE_URL="I"
JWT_SECRET_KEY = ""